title:Gillani
author:arham
email: arham.gillani@domain.com
description: > # Instance method(s) belong to the Object of the class, not to the class i.e. they can be called after creating the Object of the class.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
